5. Дана целочисленная квадратная матрица. Определить:
сумму элементов в тех столбцах, которые не содержат отрицательных элементов;
минимум среди сумм модулей элементов диагоналей, параллельных побочной диагонали
матрицы.

Инициализирую матрицу и импортирую NumPy

In [2]:
import numpy as np 

In [5]:
n = int(input("Enter the size of the matrix: "))

Enter the size of the matrix: 5


In [14]:
matrix = np.random.randint(-20, 100, (n, n))
print(matrix)

[[ 13  59  83  69  -4]
 [ 32  33   4  20  33]
 [ 49  34  25 -17  96]
 [ -5   7  90  13  76]
 [ 53  82  49  94  63]]


# 1.  Сумма элементов в тех столбцах, которые не содержат отрицательных элементов

Вывожу массив boolean по столбац, в которых минимальный элемент больше нуля:

In [20]:
print(matrix.min(axis=0) > 0)

[False  True  True False False]


Здесь я уже попытался вывести только столбцы матрицы, которые не содержали отрицательных элементов:

In [25]:
print(matrix[:, matrix.min(axis=0) > 0])

[[59 83]
 [33  4]
 [34 25]
 [ 7 90]
 [82 49]]


Узнав как получить доступ к нужным мне столбцам, посчитал их сумму:

In [26]:
summa = np.sum(matrix[:, matrix.min(axis=0) > 0])
print(summa)

466


# 2. Минимум среди сумм модулей элементов диагоналей, параллельных побочной диагонали матрицы

In [2]:
import numpy as np 

In [3]:
n = int(input("Enter the size of the matrix: "))

Enter the size of the matrix: 5


In [4]:
matrix = np.random.randint(-20, 100, (n, n))
print(matrix)

[[ 72  57 -11  22  32]
 [ 90  93  99 -18  20]
 [ 93  -1  84  57 -18]
 [ 83  96   5  43  -2]
 [ 16  23  24  86 -10]]


In [5]:
old_main_diagonal = matrix.diagonal().copy()
np.fill_diagonal(matrix, np.flipud(matrix).diagonal()) 
np.fill_diagonal(np.flipud(matrix), old_main_diagonal)
print(matrix)

[[ 16  57 -11  22 -10]
 [ 90  96  99  43  20]
 [ 93  -1  84  57 -18]
 [ 83  93   5 -18  -2]
 [ 72  23  24  86  32]]


In [11]:
print(np.tril(matrix, -1))
print(np.triu(matrix, 1))

[[ 0  0  0  0  0]
 [90  0  0  0  0]
 [93 -1  0  0  0]
 [83 93  5  0  0]
 [72 23 24 86  0]]
[[  0  57 -11  22 -10]
 [  0   0  99  43  20]
 [  0   0   0  57 -18]
 [  0   0   0   0  -2]
 [  0   0   0   0   0]]
